#!/usr/bin/env python3
"""Installer — writes a small launcher into Resolve's Scripts menu folder.

Usage:  python3 install.py        (after cloning this repo anywhere)
        python3 install.py --uninstall

The launcher only embeds the absolute path of this repo and forwards the
`resolve` object Resolve injects into menu scripts. Works in Resolve FREE
and STUDIO (the menu-script path is available in both).
"""

import os
import sys

REPO = os.path.dirname(os.path.abspath(__file__))
LAUNCHER_NAME = "Resolve AI Editor.py"

LAUNCHER = '''\
# Auto-generated by resolve-ai-editor/install.py — safe to delete.
import sys
sys.path.insert(0, {repo!r})
from plugin.main import launch
launch(globals().get("resolve"))
'''


def scripts_dirs():
    """Candidate 'Scripts/Utility' menu folders per OS (user-level first)."""
    home = os.path.expanduser("~")
    if sys.platform == "win32":
        return [os.path.join(os.environ.get("APPDATA", home),
                             "Blackmagic Design", "DaVinci Resolve",
                             "Support", "Fusion", "Scripts", "Utility")]
    if sys.platform == "darwin":
        return [os.path.join(home, "Library", "Application Support",
                             "Blackmagic Design", "DaVinci Resolve",
                             "Fusion", "Scripts", "Utility")]
    return [os.path.join(home, ".local", "share", "DaVinciResolve",
                         "Fusion", "Scripts", "Utility")]


def main():
    target_dir = scripts_dirs()[0]
    target = os.path.join(target_dir, LAUNCHER_NAME)

    if "--uninstall" in sys.argv:
        if os.path.exists(target):
            os.remove(target)
            print("Removed %s" % target)
        else:
            print("Nothing to remove (%s not found)." % target)
        return

    os.makedirs(target_dir, exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(LAUNCHER.format(repo=REPO))
    print("Installed launcher: %s" % target)
    print("In Resolve: Workspace > Scripts > Utility > Resolve AI Editor")
    print("(Restart Resolve if the entry does not appear.)")


if __name__ == "__main__":
    main()
